name: flutter_weather_auth
description: Weather App with Firebase Authentication

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - versi terbaru
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0

  # Weather API
  http: ^1.2.0

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
