name: basic_layout_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/pict1.jpg
    - images/pict2.jpg
    - images/pict3.png
    - images/pict4.jfif
    - images/pict0.jpeg
    - images/pict1.jpeg
    - images/pict2.jpeg
    - images/pict3.jpeg
    - images/pict4.jpeg
    - images/pict5.jpeg
    - images/pict6.jpeg
    - images/pict7.jpeg
    - images/pict8.jpeg
    - images/pict9.jpeg
    - images/pict10.jpeg
    - images/pict11.jpeg
    - images/pict12.jpeg
    - images/pict13.jpeg
    - images/pict14.jpeg
    - images/pict15.jpeg
    - images/pict16.jpeg
    - images/pict10.jpeg
    - images/pict11.jpeg
    - images/pict12.jpeg
    - images/pict13.jpeg
    - images/pict14.jpeg
    - images/pict15.jpeg
    - images/pict16.jpeg
    - images/pict17.jpeg
    - images/pict18.jpeg
    - images/pict19.jpeg
    - images/pict20.jpeg
    - images/pict21.jpeg
    - images/pict22.jpeg
    - images/pict23.jpeg
    - images/pict24.jpeg
    - images/pict25.jpeg
    - images/pict26.jpeg
    - images/pict27.jpeg
    - images/pict28.jpeg
    - images/pict29.jpeg
    - images/pict30.jpeg
    - images/pict31.jpeg
    - images/pict32.jpeg
    - images/pict33.jpeg
